local http = {}

function http.site()
    srv=net.createServer(net.TCP)
    srv:listen(80,function(conn)
        conn:on("receive", function(conn, payload) 
            print("Payload received: "..payload)
            
            response = require("response")
            response.filter(payload)
            -- release module
            response = nil
            package.loaded["response"]=nil
            
            conn:send('HTTP/1.1 200 OK\n\n')
            conn:send('<!DOCTYPE HTML>\n')
            conn:send('<html>\n')
            conn:send('<head><meta  content="text/html; charset=utf-8">\n')
            conn:send('<title>ESP8266</title></head>\n') 
            conn:send('<body><h1>ESP8266 pimatic client</h1>\n')
            conn:send('<hr>\n')
            conn:send('<p>Pimatic Server Credentials (www.base64encode.org):</p>')
            conn:send('<form action="" method="POST">\n')
            conn:send('<input type="text" placeholder="base64 String" name="credent">')
            conn:send('<input type="submit" value="credent">')
            conn:send('</form>')
            conn:send('<hr>\n')
            conn:send('<form action="" method="POST">\n')
            conn:send('<p>Pimatic Server IP Address:</p>')
            conn:send('<input type="text" placeholder="'..pimaticServer..'" name="IPaddress">\n')
            conn:send('<input type="submit" value="Change">')
            conn:send('</form>')
            conn:send('<hr>\n')
            conn:send('<form action="" method="POST">\n')
            conn:send('<p>Pimatic Server Port:</p>')
            conn:send('<input type="text" placeholder="'..pimaticPort..'" name="Port">\n')
            conn:send('<input type="submit" value="Change">')
            conn:send('</form>')
            conn:send('<hr>\n')
            conn:send('<form action="" method="POST">\n')
            conn:send('<p>Pimatic Variable (Humidity):</p>')
            conn:send('<input type="text" placeholder="'..hum_var..'" name="hum">\n')
            conn:send('<input type="submit" value="Change">')
            conn:send('</form>')
            conn:send('<hr>\n')
            conn:send('<form action="" method="POST">\n')
            conn:send('<p>Pimatic Variable (Temperature):</p>')
            conn:send('<input type="text" placeholder="'..tem_var..'" name="tem">\n')
            conn:send('<input type="submit" value="Change">')
            conn:send('</form>')
            conn:send('<hr>\n')
            conn:send('<p>How often should your ESP8266 send data (every x seconds):</p>')
            conn:send('<form action="" method="POST">\n')
            conn:send('<input type="submit" name="interv" value="30">\n')
            conn:send('<input type="submit" name="interv" value="60">\n')
            conn:send('<input type="submit" name="interv" value="180">\n')
            conn:send('<input type="submit" name="interv" value="300">\n')
            conn:send('<hr>\n')
            conn:send('<p>Data PIN:</p>')
            conn:send('<input type="submit" name="pinNum" value="3">\n')
            conn:send('<input type="submit" name="pinNum" value="4">\n')
            conn:send('<hr>\n')
            conn:send('<p>Device connected:</p>')
            conn:send('<input type="submit" name="device" value="DS18B20">\n')
            conn:send('<input type="submit" name="device" value="DHT22">\n')
            conn:send('</form>')
            conn:send('<hr>\n')
            conn:send('<hr>\n')
            conn:send('<p>Current Configuration:</p>')
            conn:send('<p>Interval: '..interval..'</p>')
            conn:send('<p>Data PIN: '..PIN..'</p>')
            conn:send('<p>Device: '..device..'</p>')
            conn:send('<p>Pimatic IP: '..pimaticServer..'</p>')
            conn:send('<p>Pimatic Port: '..pimaticPort..'</p>')
            conn:send('<p>Humidity Variable: '..hum_var..'</p>')
            conn:send('<p>Temperature Variable: '..tem_var..'</p>')
            conn:send('<p>Last Humidity: '..hum..'</p>')
            conn:send('<p>Last Temperature: '..tem..'</p>')
            conn:send('</body></html>\n')
            conn:on("sent",function(conn) conn:close() end)
        end)
    end)    
end

return http